<?php

namespace RentBikeBundle\Repository;

/**
 * AttributeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeListRepository extends \Doctrine\ORM\EntityRepository
{

	public function FunctionName($value='')
	{
		# code...
	}
}
